
Whois Server Version 2.0

Domain names in the .com and .net domains can now be registered
with many different competing registrars. Go to http://www.internic.net
for detailed information.

   Domain Name: SECUREDNSHOST.COM
   Registrar: TUCOWS.COM CO.
   Whois Server: whois.tucows.com
   Referral URL: http://domainhelp.opensrs.net
   Name Server: NS.SECUREDNSHOST.COM
   Name Server: NS1.SECUREDNSHOST.COM
   Status: clientTransferProhibited
   Status: clientUpdateProhibited
   Updated Date: 27-jul-2011
   Creation Date: 11-jan-2002
   Expiration Date: 11-jan-2020

&gt;&gt;&gt; Last update of whois database: Sat, 10 Sep 2011 05:45:17 UTC &lt;&lt;&lt;

NOTICE: The expiration date displayed in this record is the date the
registrar's sponsorship of the domain name registration in the registry is
currently set to expire. This date does not necessarily reflect the expiration
date of the domain name registrant's agreement with the sponsoring
registrar.  Users may consult the sponsoring registrar's Whois database to
view the registrar's reported date of expiration for this registration.

TERMS OF USE: You are not authorized to access or query our Whois
database through the use of electronic processes that are high-volume and
automated except as reasonably necessary to register domain names or
modify existing registrations; the Data in VeriSign Global Registry
Services' (&quot;VeriSign&quot;) Whois database is provided by VeriSign for
information purposes only, and to assist persons in obtaining information
about or related to a domain name registration record. VeriSign does not
guarantee its accuracy. By submitting a Whois query, you agree to abide
by the following terms of use: You agree that you may use this Data only
for lawful purposes and that under no circumstances will you use this Data
to: (1) allow, enable, or otherwise support the transmission of mass
unsolicited, commercial advertising or solicitations via e-mail, telephone,
or facsimile; or (2) enable high volume, automated, electronic processes
that apply to VeriSign (or its computer systems). The compilation,
repackaging, dissemination or other use of this Data is expressly
prohibited without the prior written consent of VeriSign. You agree not to
use electronic processes that are automated and high-volume to access or
query the Whois database except as reasonably necessary to register
domain names or modify existing registrations. VeriSign reserves the right
to restrict your access to the Whois database in its sole discretion to ensure
operational stability.  VeriSign may restrict or terminate your access to the
Whois database for failure to abide by these terms of use. VeriSign
reserves the right to modify these terms at any time.

The Registry database contains ONLY .COM, .NET, .EDU domains and
Registrars.
Registrant:
 Secure Dns Host
 PO Box 3570
 Glen Ellyn, IL 60138
 US

 Domain name: SECUREDNSHOST.COM


 Administrative Contact:
    Network, Advanced  admin@securednshost.com
    PO Box 3570
    Glen Ellyn, IL 60138
    US
    630-469-9735
 Technical Contact:
    Network, Advanced  admin@securednshost.com
    PO Box 3570
    Glen Ellyn, IL 60138
    US
    630-469-9735


 Registration Service Provider:
    Advanced Network Hosts, help247@chihost.com
    1-800-955-2841
    1-630-469-9737 (fax)
    http://advancednetworkhosts.com
    +----------------------------------+
    Registration Service Provided By
    AdvancedNetworkHosts.com

    Affordable web hosting.


 Registrar of Record: TUCOWS, INC.
 Record last updated on 27-Jul-2011.
 Record expires on 11-Jan-2020.
 Record created on 11-Jan-2002.

 Registrar Domain Name Help Center:
    http://tucowsdomains.com

 Domain servers in listed order:
    NS1.SECUREDNSHOST.COM   69.65.19.235
    NS.SECUREDNSHOST.COM   69.65.27.42


 Domain status: clientTransferProhibited
                clientUpdateProhibited

The Data in the Tucows Registrar WHOIS database is provided to you by Tucows
for information purposes only, and may be used to assist you in obtaining
information about or related to a domain name's registration record.

Tucows makes this information available &quot;as is,&quot; and does not guarantee its
accuracy.

By submitting a WHOIS query, you agree that you will use this data only for
lawful purposes and that, under no circumstances will you use this data to:
a) allow, enable, or otherwise support the transmission by e-mail,
telephone, or facsimile of mass, unsolicited, commercial advertising or
solicitations to entities other than the data recipient's own existing
customers; or (b) enable high volume, automated, electronic processes that
send queries or data to the systems of any Registry Operator or
ICANN-Accredited registrar, except as reasonably necessary to register
domain names or modify existing registrations.

The compilation, repackaging, dissemination or other use of this Data is
expressly prohibited without the prior written consent of Tucows.

Tucows reserves the right to terminate your access to the Tucows WHOIS
database in its sole discretion, including without limitation, for excessive
querying of the WHOIS database or for failure to otherwise abide by this
policy.

Tucows reserves the right to modify these terms at any time.

By submitting this query, you agree to abide by these terms.

NOTE: THE WHOIS DATABASE IS A CONTACT DATABASE ONLY.  LACK OF A DOMAIN
RECORD DOES NOT SIGNIFY DOMAIN AVAILABILITY.


