Whois Server Version 1.271

   Domain Name:   natpo.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   ns1.canwest.com
   Name Server:   ns2.canwest.com
   Creation Date: 03-Mar-2010
   Updated Date:  04-Feb-2011

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: natpo.st

Administrative Contact:
   Owner:         National Post
   Contact:       Sheldon Sawchuk
   Address:       1450 Don Mills Road, Suite 300
   State:         ON
   City:          Don Mills
   Country:       CA

Status: Active

   Latitude:    43.751156
   Longitude:   -79.347382
Name Servers:
   ns1.canwest.com
   ns2.canwest.com
