
   Rights restricted by copyright. See
   http://www.dot.tk/en/pageF00.html

   Domain name:
      MANI.TK

   Organisation:
      N/A
      Mani
      N/A
      SWE  Stockholm
      Stockholm
      Sweden
      Phone: +46 270-73400
      Fax:
      E-mail: Mani@Stockholm.com

   Domain Nameservers:
      NS1.AGILITYHOSTER.COM
      NS2.AGILITYHOSTER.COM

   Domain registered: 12/11/2008
   Record will expire on: 12/11/2013
   Record maintained by: Dot TK Domain Registry

