Whois Server Version 1.271

   Domain Name:   reali.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   ns1.dnsler.com
   Name Server:   ns2.dnsler.com
   Creation Date: 14-Feb-2010
   Updated Date:  15-Jan-2011

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: reali.st

Administrative Contact:
   Owner:         DGN Teknoloji
   Contact:       REALIST
   Address:       Cumhuriyet Mah. Kurtulus Cad. 240 Sok
   City:          bursa
   Country:       TR

Status: Active

   Latitude:    40.267887
   Longitude:   29.088160
Name Servers:
   ns1.dnsler.com
   ns2.dnsler.com
