Whois Server Version 1.271

   Domain Name:   rm.st
   Registrar:     enet
   Whois at:      whois.nic.st
   Name Server:   viz.seesaws.net
   Name Server:   ns1.maihama-net.com
   Creation Date: 09-Apr-2002
   Updated Date:  15-Feb-2010

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: enet
Contact: webmaster@enet.cc

Domain name: rm.st

Administrative Contact:
   Owner:         Junko Takeuchi
   Contact:       Junko Takeuchi
   Address:       3-311-202 Ginzacho,Fushimi-ku, Kyoto
   City:          Kyoto
   Country:       JP

Status: Active

   Latitude:    35.011635
   Longitude:   135.768036
Name Servers:
   viz.seesaws.net
   ns1.maihama-net.com
