Whois Server Version 1.271

   Domain Name:   my.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   ns1.mydomain.com
   Name Server:   ns2.mydomain.com
   Creation Date: 03-Jan-2001
   Updated Date:  05-Jan-2011

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: my.st

Administrative Contact:
   Owner:         My Street Technology
   Contact:       Bryan Griffith
   Address:       PO Box 340402
   State:         OH
   City:          Columbus
   Country:       US

Status: Active

   Latitude:    40.099998
   Longitude:   -83.059998
Name Servers:
   ns1.mydomain.com
   ns2.mydomain.com
   ns3.mydomain.com
   ns4.mydomain.com
