% request from 2620:0:2e40:2:20a:95ff:fe71:cab0
% This is the Ukrainian Whois query server #F.
% Rights restricted by copyright.
%

% The object shown below is NOT in the UANIC database.
% It has been obtained by querying a remote server:
% (whois.vn.ua) at port 43.
%
% REDIRECT BEGIN


domain:  ns1.vn.ua
descr:   Whois privacy protection service
admin-c: NEST-UANIC
tech-c:  NEST-UANIC
a-rec:   193.243.158.1
changed: Whois privacy protection service
source:  VNIC


% REDIRECT END
