Whois Server Version 1.271

   Domain Name:   bsd.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   a.ns.ods.org
   Name Server:   b.ns.ods.org
   Creation Date: 16-May-2001
   Updated Date:  23-May-2011

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: bsd.st

Administrative Contact:
   Owner:         Open Domain Server
   Contact:       Jason DiCioccio
   Address:       5300 W. Mapleshade Ln
   State:         MD
   City:          Upper Marlboro
   Country:       US

Status: Active

   Latitude:    38.815948
   Longitude:   -76.749687
Name Servers:
   a.ns.ods.org
   b.ns.ods.org
   c.ns.ods.org
