Whois Server Version 1.271

   Domain Name:   forum.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   ns1.dnspro.org
   Name Server:   ns2.dnspro.org
   Creation Date: 30-Aug-2007
   Updated Date:  02-Aug-2011

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: forum.st

Administrative Contact:
   Owner:         exotikweb
   Contact:       Private Registration
   Address:       Twins II
   City:          Villeneuve
   Country:       FR

Status: Active

   Latitude:    46.745857
   Longitude:   6.868226
Name Servers:
   ns1.dnspro.org
   ns2.dnspro.org
