% request from 2620:0:2e40:2:20a:95ff:fe71:cab0
% This is the Ukrainian Whois query server #B.
% Rights restricted by copyright.
%

% The object shown below is NOT in the UANIC database.
% It has been obtained by querying a remote server:
% (pseudo.whois.ua) at port 43.
%
% REDIRECT BEGIN

domain:	 ns.cn.ua
remark: Domain exists
remark: no information. Please contact update@auto.uanic.ua
remark:
source:	TEST


% REDIRECT END
