% request from 188.72.227.95
% This is the Ukrainian Whois query server #F.
% Rights restricted by copyright.
%

% The object shown below is NOT in the UANIC database.
% It has been obtained by querying a remote server:
% (whois.od.ua) at port 43.
%
% REDIRECT BEGIN

domain:  newkvartira.od.ua
descr:   newkvartira.od.ua site
admin-c: AP1283-UANIC
tech-c:  GLAV-UANIC
nserver: ns1.j-dns.ru
nserver: ns2.j-dns.ru
mnt-by:  DRS-UANIC
status:  OK-UNTIL 20120207174329
source:  ODNIC



% REDIRECT END
