
   Rights restricted by copyright. See
   http://www.dot.tk/en/pageF00.html

   Domain name:
      DELTA-HAWKS.TK

   Organisation:
      N/A
      Paul Hammond
      8 Coniston  Gardens
      LE65 1FB  Ashby
      Leicester
      United Kingdom
      Phone: +44 01530-012345
      Fax: +44 01530-678910
      E-mail: hamhouse2@ntlworld.com

   Domain Nameservers:

   Domain registered: 03/22/2002
   Record will expire on: 02/07/2012
   Record maintained by: Dot TK Domain Registry

