%
% whois.sk-nic.sk - whois server for TLD .sk
%


Domain-name         haytalapupu.sk
Admin-id            TOMH-0091
Admin-name          Ing. Tomas Hanko
Admin-legal-form    zivnost
Admin-org.-ID       44805080
Admin-address       L. Novomeskeho 2672/5, Trencin 91108
Admin-telephone     0000000000
Admin-email         TOMH0091@gmail.com
Last-update         2011-08-31
Valid-date          2011-09-28
Domain-status       DOM_HELD

