Whois Server Version 1.271

   Domain Name:   bur.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   ns1.bur.st    (203.82.212.241)
   Name Server:   ns2.bur.st    (203.82.210.9)
   Creation Date: 07-Aug-1999
   Updated Date:  22-Feb-2010

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: bur.st

Administrative Contact:
   Owner:         Bur.st Networking Inc.
   Contact:       Paul Day
   Address:       Bur.st Networking Inc.
PO Box 5009
   State:         WA
   City:          Dalkeith
   Country:       AU

Status: Active

   Latitude:    -31.994799
   Longitude:   115.798775
Name Servers:
   ns1.bur.st
   ns2.bur.st
