Whois Server Version 1.271

   Domain Name:   ya.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   dns1.nettica.com
   Name Server:   dns2.nettica.com
   Creation Date: 03-Jan-2002
   Updated Date:  20-Dec-2010

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: ya.st

Administrative Contact:
   Owner:         Nueva Era Digital, S.L.
   Contact:       Francisco Javier Alonso
   Address:       Apartado 55
   City:          Astillero
   Country:       ES

Status: Active

   Latitude:    43.401936
   Longitude:   -3.821603
Name Servers:
   dns1.nettica.com
   dns2.nettica.com
   dns3.nettica.com
   dns4.nettica.com
   dns5.nettica.com
