Whois Server Version 1.271

   Domain Name:   minnpo.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   ns1.mydyndns.org
   Name Server:   ns2.mydyndns.org
   Creation Date: 13-Nov-2008
   Updated Date:  28-Sep-2010

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: minnpo.st

Administrative Contact:
   Owner:         MinnPost
   Contact:       Karl Pearson-Cater
   Address:       900 6TH AVE SE SUITE 220
   State:         MN
   City:          Minneapolis
   Country:       US

Status: Active

   Latitude:    44.979965
   Longitude:   -93.263840
Name Servers:
   ns1.mydyndns.org
   ns2.mydyndns.org
   ns3.mydyndns.org
   ns5.mydyndns.org
