Whois Server Version 1.271

   Domain Name:   25mail.st
   Registrar:     Bahnhof AB
   Whois at:      whois.nic.st
   Name Server:   ns1.zonomi.com
   Name Server:   ns2.zonomi.com
   Creation Date: 08-Apr-2011
   Updated Date:  08-Apr-2011

The data in the ST Registry WHOIS database is provided by The Domain Council of
Sao Tome and Principe for information purposes.

The ST Registry does not guarantee its accuracy.

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data according with
the terms and policy that is publicly available on http://www.nic.st/terms_of_service
and that you under no circumstances will use this data to allow, enable, or
otherwise support the transmission of mass unsolicited commercial advertising or
solicitations via e-mail (spam).

The Domain Council of Sao Tome reserves the right to modify these terms at any time.

Registration Service Provided By: Bahnhof AB
Contact: registry@bahnhof.se

Domain name: 25mail.st

Administrative Contact:
   Owner:         RimuHosting
   Contact:       RimuHosting
   Address:       Top floor Centreway Arcade
60 Victoria St
   City:          Cambridge
   Country:       NZ

Status: Active

   Latitude:    -37.894051
   Longitude:   175.469543
Name Servers:
   ns1.zonomi.com
   ns2.zonomi.com
